{"id":2207,"details":"\n  \n  \u003ctable\u003e\n    \u003ctr\u003e\n      \u003ctd\u003eRegion\u003c/td\u003e\n\u003ctd\u003eCorse\u003c/td\u003e\n    \u003c/tr\u003e\n    \u003ctr\u003e\n\u003ctd\u003eDepartment\u003c/td\u003e\n\u003ctd\u003eHaute-Corse\u003c/td\u003e\n\u003c/tr\u003e\n    \u003ctr\u003e\n\u003ctd\u003eCity\u003c/td\u003e\n\u003ctd\u003eBastia\u003c/td\u003e\n\u003c/tr\u003e\n    \n  \u003c/table\u003e\n  ","patient":"Patient From Corse, Haute Corse, Bastia","source":"unknown_source","status":"unreported","confirmed_at":"2020-03-06T00:00:00.000Z","created_at":"2020-03-16T10:13:31.323Z","updated_at":"2020-03-16T10:42:56.267Z","infected_by":"unknown_infection","number":1933,"urls":["https://github.com/lperez31/coronavirus-france-dataset"],"recovered_at":null,"gender":"unidentified_gender","age":0,"nationality":"unidentified_nationality","symptomatic_at":null,"slug":"france-case-1933-patient-from-corse-haute-corse-bastia","suggested_url":"france-case-1933-patient-from-corse-haute-corse-bastia","hospital_stay_length_in_days":null,"days_from_symptoms_to_confirmation":null,"without_symptoms":false,"reporting_country":"fr"}